name: Waka Readme

on:
  schedule:
    # 02.30 / 17.30  UTC+8
    - cron: '30 18,9 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    environment: name-of-environment
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "True"

          


